---
form:
  name: apps_manager_config
  label: Apps Manager
  description: Configure Apps Manager

  property_inputs:
    - reference: .push-apps-manager.enable_invitations
      label: Enable Invitations

    - reference: .push-apps-manager.display_plan_prices
      label: Display Marketplace Service Plan Prices

    - reference: .push-apps-manager.currency_lookup
      label: Supported currencies as JSON
      description: |
        Define the currency codes and associated symbols (defaults to \"{
        \"usd\": \"$\", \"eur\": \"â‚¬\" }\" if blank)

    - reference: .push-apps-manager.product_name
      label: Product Name
      description: |
        Replace "Apps Manager" in the header with a custom product name
        (defaults to "Apps Manager" if blank)

    - reference: .push-apps-manager.marketplace_name
      label: Marketplace Name
      description: Replaces "Marketplace" on the Apps Manager Marketplace Pages.

    - reference: .push-apps-manager.nav_links
      label: Customize Sidebar Links
      description: |
        You may configure up to 10 links in the Apps Manager sidebar.
      property_inputs:
        - reference: name
          label: Link text

        - reference: href
          label: URL
