---
name: application_containers
label: App Containers
description: App Containers
markdown: |
  For help configuring these fields, see
  [App Containers](https://docs.pivotal.io/pivotalcf/2-11/customizing/installing-pcf-is.html#application_containers)
  in _Installing Isolation Segment_ in the VMware Tanzu documentation.

property_inputs:
- reference: .properties.route_integrity
  label: Gorouter app identity verification
  selector_property_inputs:
  - reference: .properties.route_integrity.tls_verify
    label: The Gorouter uses TLS to verify app identity
  - reference: .properties.route_integrity.mutual_tls_verify
    label: The Gorouter and apps use mutual TLS to verify each other's identity

- reference: .isolated_diego_cell.insecure_docker_registry_list
  label: Private Docker insecure registry allow list
  description: |
    A comma-separated list of private Docker image registries that are secured
    with self-signed certificates.
  placeholder: |
    10.10.10.10:8888,example.com:8888

- reference: .properties.garden_disk_cleanup
  label: Docker images disk cleanup scheduling on Diego Cell VMs
  selector_property_inputs:
  - reference: .properties.garden_disk_cleanup.never
    label: Never clean up Diego Cell disk space

  - reference: .properties.garden_disk_cleanup.routine
    label: Routinely clean up Diego Cell disk space

  - reference: .properties.garden_disk_cleanup.reserved
    label: Clean up disk space once usage fills disk
    property_inputs:
      - reference: .properties.garden_disk_cleanup.reserved.reserved_space_for_other_jobs_in_mb
        label: Reserved disk space for other jobs
        description: |
          The amount of space the garbage collection algorithm should attempt to
          keep free for other jobs. Enter value in MB.

- reference: .properties.enable_garden_containerd_mode
  label: Enable containerd delegation
  description: |
    Garden delegates container create and destroy operations to containerd.

- reference: .properties.nfs_volume_driver
  label: NFSv3 volume services
  description: |
    Allows app developers to bind existing NFS volumes to apps
    for shared file access.
  selector_property_inputs:
    - reference: .properties.nfs_volume_driver.enable
      label: Enable
      property_inputs:
        - reference: .properties.nfs_volume_driver.enable.ldap_service_account_user
          label: LDAP service account user

        - reference: .properties.nfs_volume_driver.enable.ldap_service_account_password
          label: LDAP service account password

        - reference: .properties.nfs_volume_driver.enable.ldap_server_host
          label: LDAP server host

        - reference: .properties.nfs_volume_driver.enable.ldap_server_port
          label: LDAP server port
          description: |
            The default is 389.

        - reference: .properties.nfs_volume_driver.enable.ldap_user_fqdn
          label: LDAP user search base
          description: |
            The location in the LDAP directory tree from which any LDAP user
            search begins.
          placeholder: "cn=Users,dc=corp,dc=test,dc=com"

        - reference: .properties.nfs_volume_driver.enable.ldap_ca_cert
          label: LDAP server CA certificate
          description: |
            Only required for LDAP integration with SSL.

    - reference: .properties.nfs_volume_driver.disable
      label: Disable

- reference: .properties.app_log_rate_limiting
  label: App log rate limit (beta)
  description: |
    Limit the number of log lines an app instance can generate per second.
  selector_property_inputs:
    - reference: .properties.app_log_rate_limiting.enable
      label: Enable
      property_inputs:
        - reference: .properties.app_log_rate_limiting.enable.max_log_lines_per_second
          label: Maximum app log lines per second
          description: |
            The default value is 100.

    - reference: .properties.app_log_rate_limiting.disable
      label: Disable
