---
name: application_security_groups
label: App Security Groups
description: App Security Groups
markdown: |
  For help configuring these fields, see
  [Configure App Security Groups](https://docs.pivotal.io/pivotalcf/2-11/customizing/configure-pas.html#app-security)
  in _Configuring TAS for VMs_ in the VMware Tanzu documentation.

property_inputs:
  - reference: .properties.security_acknowledgement
    label: Type "X" to acknowledge this requirement.
