---
name: smtp_config
label: Email Notifications
description: |
  Configure Simple Mail Transfer Protocol for the Notifications application
  to send email notifications about your deployment. This application is
  deployed as an errand in Application Service. If you do not need this service,
  leave this section blank and disable the Notifications and Notifications UI
  errands.

property_inputs:
  - reference: .properties.smtp_from
    label: From Email
    description: The email address from which emails are sent.

  - reference: .properties.smtp_address
    label: SMTP Server Address
    description: The SMTP address of the server that sends emails.

  - reference: .properties.smtp_port
    label: SMTP Server Port
    description: The port of the SMTP server that sends emails.

  - reference: .properties.smtp_credentials
    label: SMTP Server Credentials
    description: |
      The credentials for the SMTP server that sends emails. Note: Operators
      should take care to escape any special characters included here.

  - reference: .properties.smtp_enable_starttls_auto
    label: SMTP Enable Automatic STARTTLS

  - reference: .properties.smtp_auth_mechanism
    label: SMTP Authentication Mechanism

  - reference: .properties.smtp_crammd5_secret
    label: SMTP CRAMMD5 secret
